public enum ListenType
{
    ANY=0,
    PLAYER_IDLE,
    PLAYER_SLOW_RUN,
    PLAYER_FAST_RUN,
    PLAYER_HIT,
    PLAYER_SKILL,
    PLAYER_GET_HIT,
    GET_HIT_BY_ASIAN,
    GET_HIT_BY_VIKING,
    GET_HIT_BY_ORC,
    GET_HIT_BY_TUNGUS,
    PLAYER_DEATH,
    TITAN_ATTACK_EFFECT,
    SKILL_ASIAN_ENEMY_EFFECT,
    SKILL_ASIAN_CHIEFTAIN_EFFECT,
    SKILL_ASIAN_CHIEFTAIN_AI_EFFECT,
    SKILL_VIKING_ENEMY_EFFECT,
    SKILL_VIKING_CHIEFTAIN_EFFECT,
    SKILL_ORC_ENEMY_EFFECT,
    SKILL_ORC_CHIEFTAIN_EFFECT,
    SKILL_TUNGUS_ALLY_EFFECT,
    SKILL_TUNGUS_CHIEFTAIN_EFFECT,
    SKILL_TITAN_ASIAN_EFFECT,
    SKILL_TITAN_ORC_EFFECT,
    SKILL_TITAN_TUNGUS_EFFECT,
    SKILL_TITAN_TUNGUS_ALLY_EFFECT,
    SKILL_TITAN_VIKING_EFFECT,
    SKILL_TITAN_VIKING_ENEMY_EFFECT,
    TUNGUS_CHIEFTAIN_SELECTED,
    TUNGUS_VILLAGER_SELECTEC,
}

public enum ChieftainType
{
    UNKNOWN =0,
    ASIAN,
    VIKING,
    ORC,
    TUNGUS,
    TITAN_ORC,
    TITAN_TUNGUS,
    TITAN_VIKING,
    TITAN_ASIAN
}

public enum TribeType
{
    UNKNOWN=0,
    ASIAN,
    VIKING,
    ORC,
    TUNGUS,
    TITAN
}
public enum RoleType
{
    UNKNOWN=0,
    CHIEFTAIN,
    VILLAGER
}
public enum UIType
{
    UNKNOWN,
    SCREEN,
    POPUP,
    NOTIFY,
    OVERLAP
}

